/**
 * Personal Injury Case Type Definitions
 * Based on Ontario SABS and Tort practice requirements
 */

export interface PICase {
  id: string
  firmId: string // Required for multi-tenant RLS
  title: string
  clientId: string

  // Core Dates
  dateOfLoss: string // DOL - The "Big Bang" event
  dateOpened: string
  limitationDate?: string // Auto-calculated, adjusted for minors

  // Dual-Track System
  sabs: SABSClaim
  tort: TortClaim
  hasSABS?: boolean // Computed: true if case has an associated SABS claim
  
  // Status
  status: CaseStatus
  stage: CaseStage
  
  // Financial
  estimatedValue: number
  currentOffer?: number
  disbursements: Disbursement[]
  totalDisbursements: number
  
  // Evidence
  medicalProviders: MedicalProvider[]
  expertReports: ExpertReport[]
  
  // Tasks & Deadlines
  criticalDeadlines: Deadline[]
  undertakings: Undertaking[]
  
  // Metadata
  notes: string[]
  tags: string[]
  createdAt?: string
  updatedAt?: string
  
  // Team Assignment
  primaryLawyerId?: string // Senior or Junior Lawyer assigned to case
  assignedTeamMembers?: string[] // Array of user IDs (clerks, supporting lawyers)
  assignedParalegalId?: string // Paralegal handling SABS work
}

export interface SABSClaim {
  caseId: string
  
  // Application Phase
  noticeDate?: string // DOL + 7 days
  ocf1ReceivedDate?: string
  ocf1Deadline?: string // Received + 30 days
  ocf1SubmittedDate?: string
  
  // Disability Certificate
  ocf3ExpiryDate?: string
  ocf3RenewalAlert?: boolean // Alert 30 days prior
  
  // Benefit Election
  benefitElection?: BenefitElection
  electedBenefitType?: 'IRB' | 'NEB' | 'Caregiver'
  
  // Treatment Funding
  migStatus: 'MIG' | 'Non-MIG' | 'CAT'
  migBustStatus?: 'In Progress' | 'Approved' | 'Denied'
  ocf18Submissions: OCF18Submission[]
  
  // CAT Determination
  catStatus: 'Not Assessed' | 'Pending' | 'Approved' | 'Denied'
  catApplicationDate?: string
  catAssessmentDate?: string
  
  // Benefits Paid
  irbPaid: number
  medicalPaid: number
  attendantCarePaid: number
  totalPaid: number
  
  // LAT Disputes
  latApplications: LATApplication[]
  
  // Policy Limits
  medicalRehabLimit: number // $65k standard, $1M CAT
  attendantCareLimit: number
}

export interface TortClaim {
  caseId: string
  
  // Limitation Period
  limitationDate: string // DOL + 2 years (adjusted for minors)
  limitationStatus: 'Active' | 'Expired' | 'Extended'
  
  // Notice & Pleadings
  noticeOfIntentDate?: string // DOL + 120 days
  statementOfClaimIssued?: string
  statementOfClaimServed?: string
  statementOfDefenseReceived?: string
  
  // Parties
  defendants: Defendant[]
  juryNoticeFiled: boolean
  
  // Discovery
  discoveryDate?: string
  discoveryCompleted: boolean
  discoveryTranscriptReceived?: string
  plaintiffExamDate?: string
  plaintiffExamCompleted?: boolean
  defendantExamDate?: string
  defendantExamCompleted?: boolean
  discoveryAttempts?: DiscoveryAttempt[]
  
  // Undertakings
  plaintiffUndertakings: Undertaking[]
  defenseUndertakings: Undertaking[]
  
  // Affidavit of Documents
  aodDrafted: boolean
  aodServed?: string
  scheduleA: Document[]
  scheduleB: Document[]
  scheduleC: Document[]
  
  // Pre-Trial & Trial
  trialRecordServed?: string
  setDownDate?: string
  rule48DismissalDate?: string // Issuance + 5 years
  preTrialDate?: string
  preTrialBriefFiled?: boolean
  trialDate?: string
  juryNoticeDate?: string // When jury notice was filed

  // Trial Outcome
  trialOutcome?: TrialOutcome

  // Pre-Trial Checklist Progress (persisted)
  preTrialChecklistProgress?: Record<string, boolean>

  // Settlement
  offers: SettlementOffer[]
  currentOffer?: SettlementOffer
}

export interface TrialOutcome {
  result: 'Plaintiff Verdict' | 'Defense Verdict' | 'Settled at Trial' | 'Mistrial' | 'Dismissed'
  judgmentDate?: string
  judgmentAmount?: number
  costsAwarded?: number
  interestAwarded?: number
  totalJudgment?: number
  appealFiled?: boolean
  appealDate?: string
  appealStatus?: 'Pending' | 'Allowed' | 'Dismissed' | 'Settled'
  notes?: string
}

export interface DiscoveryAttempt {
  id: string
  type: 'Plaintiff' | 'Defendant'
  scheduledDate: string
  status: 'Scheduled' | 'Completed' | 'Cancelled' | 'Adjourned' | 'Refused'
  reason?: string // Reason for cancellation/adjournment/refusal
  location?: string
  reporter?: string // Court reporter name
  notes?: string
  createdAt: string
}

export interface Deadline {
  id: string
  caseId: string
  type: DeadlineType
  description: string
  dueDate: string
  status: 'Active' | 'Completed' | 'Overdue' | 'Missed'
  autoGenerated: boolean
  critical: boolean // Red Zone item
  daysRemaining: number
}

export type DeadlineType =
  | 'SABS_NOTICE' // DOL + 7 days
  | 'OCF1_DEADLINE' // Received + 30 days
  | 'OCF3_RENEWAL' // Expiry - 30 days
  | 'OCF18_DEEMED_APPROVAL' // Submission + 10 business days
  | 'TORT_NOTICE' // DOL + 120 days
  | 'LIMITATION_PERIOD' // DOL + 2 years
  | 'LAT_LIMITATION' // Denial + 2 years
  | 'RULE48_DISMISSAL' // Issuance + 5 years
  | 'PRETRIAL_BRIEF' // Pre-Trial - 5 days
  | 'EXPERT_REPORT' // Pre-Trial - 90 days
  | 'RESPONDING_REPORT' // Pre-Trial - 60 days

export interface OCF18Submission {
  id: string
  caseId: string
  submissionDate: string
  treatmentType: string
  amount: number
  status: 'Pending' | 'Approved' | 'Partially Approved' | 'Denied' | 'Deemed Approved'
  responseDate?: string
  responseDeadline: string // Submission + 10 business days
  deemedApprovalDate?: string
}

export interface LATApplication {
  id: string
  caseId: string
  denialDate: string
  denialType: string
  applicationFiled?: string
  limitationDate: string // Denial + 2 years
  caseConferenceDate?: string
  hearingDate?: string
  status: 'Pending' | 'Filed' | 'Settled' | 'Hearing Scheduled' | 'Completed'
  deniedBenefitValue: number
}

export interface Undertaking {
  id: string
  caseId: string
  type: 'Plaintiff' | 'Defense'
  description: string
  requestedDate: string
  assignedTo?: string // Client ID or staff member
  status: 'Requested' | 'Refused' | 'Under Advisement' | 'Answered' | 'Served'
  dueDate?: string
  completedDate?: string
  notes?: string
}

export interface MedicalProvider {
  id: string
  name: string
  type: 'GP' | 'Specialist' | 'Hospital' | 'Clinic' | 'Physio' | 'Chiro' | 'Other'
  recordsObtained: boolean
  lastRecordDate?: string
  recordsRequested?: string
  gapDetected: boolean
  gapStartDate?: string
  gapEndDate?: string
}

export interface ExpertReport {
  id: string
  caseId: string
  expertName: string
  expertType: 'Orthopedic' | 'Neurological' | 'Psychological' | 'Vocational' | 'Actuarial' | 'Other'
  retainedDate: string
  recordsSentDate?: string
  assessmentDate?: string
  draftReceivedDate?: string
  finalServedDate?: string
  status: 'Retained' | 'Records Sent' | 'Assessment Scheduled' | 'Draft Received' | 'Final Served'
  rule53Compliant: boolean
  preTrialDeadline: string // Pre-Trial - 90 days
}

export interface Disbursement {
  id: string
  caseId: string
  date: string
  description: string
  amount: number
  category: 'Expert' | 'Court Fees' | 'Transcripts' | 'Medical Records' | 'Process Serving' | 'Other'
  assessable: boolean // Recoverable from defendant
  paid: boolean
  invoiceNumber?: string
}

export interface SettlementOffer {
  id: string
  caseId: string
  date: string
  amount: number
  type: 'Plaintiff' | 'Defendant'
  grossAmount: number
  netAmount?: number // After deductions
  status: 'Open' | 'Accepted' | 'Rejected' | 'Countered'
  expiresDate?: string
}

export interface Defendant {
  id: string
  name: string
  role: 'Driver' | 'Owner' | 'Lessee'
  insuranceCompany: string
  policyNumber?: string
  served: boolean
  servedDate?: string
}

export interface BenefitElection {
  irbAmount: number
  nebAmount: number
  caregiverAmount: number
  selected: 'IRB' | 'NEB' | 'Caregiver'
  electionDate: string
}

export interface Document {
  id: string
  caseId: string
  title: string
  type: string
  date: string
  schedule: 'A' | 'B' | 'C'
  url?: string
}

export type CaseStatus = 'Active' | 'Stalled' | 'Critical' | 'Settled' | 'Closed'
export type CaseStage = 
  | 'Intake'
  | 'SABS Application'
  | 'Discovery'
  | 'Set Down'
  | 'Pre-Trial'
  | 'Trial Ready'
  | 'Mediation'
  | 'Settled'
  | 'Trial'

