/**
 * Timeline Auto-Populator
 * Automatically generates all critical deadlines from Date of Loss
 * Based on Ontario SABS and Tort practice requirements
 */

import { Deadline, DeadlineType, PICase } from '@/types/pi-case'

/**
 * Calculate business days (excludes weekends and holidays)
 */
function addBusinessDays(date: Date, days: number): Date {
  const result = new Date(date)
  let addedDays = 0
  
  while (addedDays < days) {
    result.setDate(result.getDate() + 1)
    const dayOfWeek = result.getDay()
    // Skip weekends (Saturday = 6, Sunday = 0)
    if (dayOfWeek !== 0 && dayOfWeek !== 6) {
      addedDays++
    }
  }
  
  return result
}

/**
 * Check if date is a statutory holiday in Ontario
 */
function isHoliday(date: Date): boolean {
  const year = date.getFullYear()
  const month = date.getMonth()
  const day = date.getDate()
  
  // New Year's Day
  if (month === 0 && day === 1) return true
  // Family Day (3rd Monday in February)
  if (month === 1 && day >= 15 && day <= 21 && date.getDay() === 1) return true
  // Good Friday (calculate Easter - 2 days)
  // Victoria Day (Monday before May 25)
  // Canada Day (July 1)
  if (month === 6 && day === 1) return true
  // Labour Day (1st Monday in September)
  if (month === 8 && day <= 7 && date.getDay() === 1) return true
  // Thanksgiving (2nd Monday in October)
  if (month === 9 && day >= 8 && day <= 14 && date.getDay() === 1) return true
  // Christmas
  if (month === 11 && day === 25) return true
  // Boxing Day
  if (month === 11 && day === 26) return true
  
  return false
}

/**
 * Calculate limitation period accounting for minors
 */
function calculateLimitationDate(dateOfLoss: Date, clientBirthDate?: Date): Date {
  const baseLimitation = new Date(dateOfLoss)
  baseLimitation.setFullYear(baseLimitation.getFullYear() + 2)
  
  if (!clientBirthDate) return baseLimitation
  
  const ageAtAccident = dateOfLoss.getFullYear() - clientBirthDate.getFullYear()
  
  // If minor at time of accident, limitation doesn't start until 18th birthday
  if (ageAtAccident < 18) {
    const eighteenthBirthday = new Date(clientBirthDate)
    eighteenthBirthday.setFullYear(eighteenthBirthday.getFullYear() + 18)
    
    // Limitation is 2 years from 18th birthday
    const limitationDate = new Date(eighteenthBirthday)
    limitationDate.setFullYear(limitationDate.getFullYear() + 2)
    
    return limitationDate
  }
  
  return baseLimitation
}

/**
 * Generate all critical deadlines from Date of Loss
 */
export function generateTimelineFromDOL(
  dateOfLoss: string,
  caseId: string,
  clientBirthDate?: string,
  statementOfClaimIssued?: string
): Deadline[] {
  const dol = new Date(dateOfLoss)
  const birthDate = clientBirthDate ? new Date(clientBirthDate) : undefined
  const deadlines: Deadline[] = []
  
  // SABS Deadlines
  // Notice within 7 days
  const noticeDeadline = new Date(dol)
  noticeDeadline.setDate(noticeDeadline.getDate() + 7)
  deadlines.push({
    id: `sabs-notice-${caseId}`,
    caseId,
    type: 'SABS_NOTICE',
    description: 'SABS Notice to Insurer (DOL + 7 days)',
    dueDate: noticeDeadline.toISOString(),
    status: 'Active',
    autoGenerated: true,
    critical: true,
    daysRemaining: Math.ceil((noticeDeadline.getTime() - Date.now()) / (1000 * 60 * 60 * 24)),
  })
  
  // Tort Notice of Intent (DOL + 120 days)
  const noticeOfIntent = new Date(dol)
  noticeOfIntent.setDate(noticeOfIntent.getDate() + 120)
  deadlines.push({
    id: `tort-notice-${caseId}`,
    caseId,
    type: 'TORT_NOTICE',
    description: 'Notice of Intent to Sue (DOL + 120 days)',
    dueDate: noticeOfIntent.toISOString(),
    status: 'Active',
    autoGenerated: true,
    critical: true,
    daysRemaining: Math.ceil((noticeOfIntent.getTime() - Date.now()) / (1000 * 60 * 60 * 24)),
  })
  
  // Limitation Period (DOL + 2 years, adjusted for minors)
  const limitationDate = calculateLimitationDate(dol, birthDate)
  deadlines.push({
    id: `limitation-${caseId}`,
    caseId,
    type: 'LIMITATION_PERIOD',
    description: `Limitation Period Expires${birthDate && new Date(dateOfLoss).getFullYear() - birthDate.getFullYear() < 18 ? ' (Adjusted for Minor)' : ''}`,
    dueDate: limitationDate.toISOString(),
    status: 'Active',
    autoGenerated: true,
    critical: true,
    daysRemaining: Math.ceil((limitationDate.getTime() - Date.now()) / (1000 * 60 * 60 * 24)),
  })
  
  // Rule 48 Dismissal (5 years from Statement of Claim issuance)
  if (statementOfClaimIssued) {
    const rule48Date = new Date(statementOfClaimIssued)
    rule48Date.setFullYear(rule48Date.getFullYear() + 5)
    deadlines.push({
      id: `rule48-${caseId}`,
      caseId,
      type: 'RULE48_DISMISSAL',
      description: 'Rule 48 Administrative Dismissal (5 years from issuance)',
      dueDate: rule48Date.toISOString(),
      status: 'Active',
      autoGenerated: true,
      critical: true,
      daysRemaining: Math.ceil((rule48Date.getTime() - Date.now()) / (1000 * 60 * 60 * 24)),
    })
  }
  
  return deadlines
}

/**
 * Generate OCF-1 deadline (30 days from receipt of package)
 */
export function generateOCF1Deadline(
  packageReceivedDate: string,
  caseId: string
): Deadline {
  const received = new Date(packageReceivedDate)
  const deadline = new Date(received)
  deadline.setDate(deadline.getDate() + 30)
  
  return {
    id: `ocf1-${caseId}`,
    caseId,
    type: 'OCF1_DEADLINE',
    description: 'OCF-1 Application Deadline (Received + 30 days)',
    dueDate: deadline.toISOString(),
    status: 'Active',
    autoGenerated: true,
    critical: true,
    daysRemaining: Math.ceil((deadline.getTime() - Date.now()) / (1000 * 60 * 60 * 24)),
  }
}

/**
 * Generate OCF-3 renewal alert (30 days before expiry)
 */
export function generateOCF3RenewalAlert(
  expiryDate: string,
  caseId: string
): Deadline {
  const expiry = new Date(expiryDate)
  const alertDate = new Date(expiry)
  alertDate.setDate(alertDate.getDate() - 30)
  
  return {
    id: `ocf3-renewal-${caseId}`,
    caseId,
    type: 'OCF3_RENEWAL',
    description: 'OCF-3 Renewal Alert (30 days before expiry)',
    dueDate: alertDate.toISOString(),
    status: 'Active',
    autoGenerated: true,
    critical: true,
    daysRemaining: Math.ceil((alertDate.getTime() - Date.now()) / (1000 * 60 * 60 * 24)),
  }
}

/**
 * Generate OCF-18 deemed approval deadline (10 business days from submission)
 */
export function generateOCF18DeemedApproval(
  submissionDate: string,
  caseId: string,
  ocf18Id: string
): Deadline {
  const submitted = new Date(submissionDate)
  const deadline = addBusinessDays(submitted, 10)
  
  return {
    id: `ocf18-deemed-${ocf18Id}`,
    caseId,
    type: 'OCF18_DEEMED_APPROVAL',
    description: 'OCF-18 Deemed Approval (10 business days from submission)',
    dueDate: deadline.toISOString(),
    status: 'Active',
    autoGenerated: true,
    critical: true,
    daysRemaining: Math.ceil((deadline.getTime() - Date.now()) / (1000 * 60 * 60 * 24)),
  }
}

/**
 * Generate LAT limitation deadline (2 years from denial)
 */
export function generateLATLimitation(
  denialDate: string,
  caseId: string,
  latId: string
): Deadline {
  const denial = new Date(denialDate)
  const deadline = new Date(denial)
  deadline.setFullYear(deadline.getFullYear() + 2)
  
  return {
    id: `lat-limitation-${latId}`,
    caseId,
    type: 'LAT_LIMITATION',
    description: 'LAT Application Deadline (Denial + 2 years)',
    dueDate: deadline.toISOString(),
    status: 'Active',
    autoGenerated: true,
    critical: true,
    daysRemaining: Math.ceil((deadline.getTime() - Date.now()) / (1000 * 60 * 60 * 24)),
  }
}

/**
 * Generate Pre-Trial brief deadline (5 days before Pre-Trial)
 */
export function generatePreTrialBriefDeadline(
  preTrialDate: string,
  caseId: string
): Deadline {
  const preTrial = new Date(preTrialDate)
  const deadline = new Date(preTrial)
  deadline.setDate(deadline.getDate() - 5)
  
  return {
    id: `pretrial-brief-${caseId}`,
    caseId,
    type: 'PRETRIAL_BRIEF',
    description: 'Pre-Trial Brief Deadline (Pre-Trial - 5 days)',
    dueDate: deadline.toISOString(),
    status: 'Active',
    autoGenerated: true,
    critical: true,
    daysRemaining: Math.ceil((deadline.getTime() - Date.now()) / (1000 * 60 * 60 * 24)),
  }
}

/**
 * Generate expert report deadline (90 days before Pre-Trial)
 */
export function generateExpertReportDeadline(
  preTrialDate: string,
  caseId: string,
  expertId: string
): Deadline {
  const preTrial = new Date(preTrialDate)
  const deadline = new Date(preTrial)
  deadline.setDate(deadline.getDate() - 90)
  
  return {
    id: `expert-report-${expertId}`,
    caseId,
    type: 'EXPERT_REPORT',
    description: 'Expert Report Deadline (Pre-Trial - 90 days)',
    dueDate: deadline.toISOString(),
    status: 'Active',
    autoGenerated: true,
    critical: true,
    daysRemaining: Math.ceil((deadline.getTime() - Date.now()) / (1000 * 60 * 60 * 24)),
  }
}

/**
 * Update deadline days remaining
 */
export function updateDeadlineDaysRemaining(deadline: Deadline): Deadline {
  const dueDate = new Date(deadline.dueDate)
  const now = Date.now()
  const daysRemaining = Math.ceil((dueDate.getTime() - now) / (1000 * 60 * 60 * 24))
  
  let status = deadline.status
  if (daysRemaining < 0 && deadline.status === 'Active') {
    status = 'Overdue'
  } else if (daysRemaining < -7 && deadline.status === 'Overdue') {
    status = 'Missed'
  }
  
  return {
    ...deadline,
    daysRemaining,
    status,
  }
}

